import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { toast } from "sonner";
import {
  FileText,
  Loader2,
  Download,
  ArrowLeft,
  ArrowRight,
  Sparkles,
} from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useDealAnalysisStore } from "@/stores/dealAnalysisStore";
import { SAStrategyInputs } from "@/types/dealAnalysis";
import { pdf, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

// PDF styles
const pdfStyles = StyleSheet.create({
  page: { padding: 50, fontSize: 12, fontFamily: "Helvetica", lineHeight: 1.6 },
  title: { fontSize: 18, marginBottom: 20, fontFamily: "Helvetica-Bold", textAlign: "center" },
  date: { fontSize: 10, marginBottom: 20, color: "#666", textAlign: "right" },
  paragraph: { marginBottom: 12 },
  footer: { marginTop: 30, fontSize: 10, color: "#999", textAlign: "center" },
});

function PitchPDF({ pitchText, propertyAddress }: { pitchText: string; propertyAddress: string }) {
  const paragraphs = pitchText.split("\n").filter((p) => p.trim());
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <Text style={pdfStyles.title}>Guaranteed Rent Proposal</Text>
        <Text style={pdfStyles.date}>{new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</Text>
        {paragraphs.map((p, i) => (
          <View key={i} style={pdfStyles.paragraph}>
            <Text>{p}</Text>
          </View>
        ))}
        <Text style={pdfStyles.footer}>
          Generated by DealFlow — {propertyAddress}
        </Text>
      </Page>
    </Document>
  );
}

export function LandlordPitchGenerator() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { analysis, strategyInput, setStep } = useDealAnalysisStore();

  const saInputs = strategyInput.inputs as SAStrategyInputs;
  const propertyAddress = analysis?.propertyAddress || analysis?.postcode || "Property";

  const [operatorName, setOperatorName] = useState(user?.user_metadata?.full_name || "");
  const [keyBenefits, setKeyBenefits] = useState(
    "guaranteed monthly rent, professional property management, no void periods, regular property inspections"
  );
  const [monthlyOffer, setMonthlyOffer] = useState(
    String(saInputs.propertyStrategy === "r2sa" ? saInputs.monthlyLeaseCost : 0)
  );

  const [pitchText, setPitchText] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const handleGenerate = async () => {
    if (!monthlyOffer || parseInt(monthlyOffer) <= 0) {
      toast.error("Please enter a monthly rent offer");
      return;
    }

    setIsGenerating(true);
    setPitchText("");

    try {
      const { data, error } = await supabase.functions.invoke("generate-landlord-pitch", {
        body: {
          propertyAddress,
          monthlyOffer: parseInt(monthlyOffer),
          keyBenefits,
          operatorName,
        },
      });

      if (error) throw error;

      if (data?.requiresUpgrade) {
        toast.error("Free plan limit reached. Upgrade to generate more pitch letters.", {
          action: {
            label: "Upgrade",
            onClick: () => navigate("/settings"),
          },
        });
        return;
      }

      if (data?.error) {
        throw new Error(data.error);
      }

      setPitchText(data.pitch);
      toast.success("Pitch letter generated!");
    } catch (error: any) {
      console.error("Pitch generation error:", error);
      toast.error(error.message || "Failed to generate pitch letter");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadPDF = async () => {
    if (!pitchText) return;
    setIsDownloading(true);

    try {
      const blob = await pdf(
        <PitchPDF pitchText={pitchText} propertyAddress={propertyAddress} />
      ).toBlob();

      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `landlord-pitch-${propertyAddress.replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success("PDF downloaded!");
    } catch (error) {
      console.error("PDF download error:", error);
      toast.error("Failed to generate PDF");
    } finally {
      setIsDownloading(false);
    }
  };

  const handleAddToPipeline = () => {
    navigate("/pipeline", {
      state: {
        prefill: {
          address: propertyAddress,
          monthlyOffer: parseInt(monthlyOffer),
          strategy: saInputs.propertyStrategy,
        },
      },
    });
  };

  return (
    <Card className="max-w-3xl mx-auto">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <div className="p-2 rounded-lg bg-primary/10">
            <FileText className="h-5 w-5 text-primary" />
          </div>
          Landlord Pitch Generator
        </CardTitle>
        <p className="text-muted-foreground">
          Generate a professional guaranteed rent proposal for this property.
        </p>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Inputs */}
        <div className="space-y-4 p-4 rounded-lg border bg-muted/30">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Your name / company</Label>
              <Input
                value={operatorName}
                onChange={(e) => setOperatorName(e.target.value)}
                placeholder="Your name or company name"
              />
            </div>
            <div className="space-y-2">
              <Label>Monthly rent offer (£) *</Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">£</span>
                <Input
                  className="pl-7"
                  value={monthlyOffer}
                  onChange={(e) => setMonthlyOffer(e.target.value.replace(/[^0-9]/g, ""))}
                  placeholder="1,200"
                />
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <Label>Property address</Label>
            <Input value={propertyAddress} disabled className="bg-muted" />
          </div>

          <div className="space-y-2">
            <Label>Key benefits to highlight</Label>
            <Textarea
              value={keyBenefits}
              onChange={(e) => setKeyBenefits(e.target.value)}
              placeholder="Guaranteed rent, professional management..."
              rows={2}
            />
          </div>
        </div>

        {/* Generate button */}
        {!pitchText && (
          <Button
            onClick={handleGenerate}
            disabled={isGenerating || !monthlyOffer}
            size="lg"
            className="w-full"
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating pitch letter...
              </>
            ) : (
              <>
                <Sparkles className="mr-2 h-4 w-4" />
                Generate Landlord Pitch
              </>
            )}
          </Button>
        )}

        {/* Generated pitch */}
        {pitchText && (
          <div className="space-y-4">
            <div className="rounded-lg border bg-background">
              <div className="p-3 border-b bg-muted/50 flex items-center justify-between">
                <span className="text-sm font-medium">Generated Pitch Letter</span>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleGenerate}
                  disabled={isGenerating}
                >
                  {isGenerating ? (
                    <Loader2 className="h-3 w-3 animate-spin" />
                  ) : (
                    "Regenerate"
                  )}
                </Button>
              </div>
              <ScrollArea className="h-[400px] p-4">
                <div className="whitespace-pre-wrap text-sm leading-relaxed">
                  {pitchText}
                </div>
              </ScrollArea>
            </div>

            <div className="flex flex-col sm:flex-row gap-3">
              <Button
                onClick={handleDownloadPDF}
                disabled={isDownloading}
                variant="outline"
                className="flex-1"
              >
                {isDownloading ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Download className="mr-2 h-4 w-4" />
                )}
                Download as PDF
              </Button>
              <Button
                onClick={handleAddToPipeline}
                className="flex-1"
              >
                <ArrowRight className="mr-2 h-4 w-4" />
                Add to Pipeline
              </Button>
            </div>
          </div>
        )}

        {/* Navigation */}
        <div className="flex justify-between pt-4 border-t">
          <Button variant="outline" onClick={() => setStep(4)} size="lg">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Results
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
